image: maven:3.6.0-jdk-8-alpine

variables:
  MAVEN_PARENT_DIR: "./de.fhg.aisec.mark.parent"
  #MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -f $MAVEN_PARENT_DIR"
  MAVEN_CLI_OPTS: "--batch-mode -f $MAVEN_PARENT_DIR"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS install -DskipTests

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests


