image: maven:3.6-jdk-8-alpine

variables:
  MAVEN_PARENT_DIR: "./de.fraunhofer.aisec.mark.parent"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -f $MAVEN_PARENT_DIR"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

##cache:
##  paths:
##    - .m2/repository/
##    - target/

build:
  stage: build
  tags:
    - netsec
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests
    - mvn $MAVEN_CLI_OPTS deploy -X -DskipTests
