/*
 * generated by Xtext 2.14.0
 */
package de.fhg.aisec.mark.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MarkDslProposalProvider extends AbstractMarkDslProposalProvider {
}
