/*
 * generated by Xtext 2.14.0
 */
package de.fraunhofer.aisec.mark.validation


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MarkDslValidator extends AbstractMarkDslValidator {
	
}
