/*
 * generated by Xtext 2.14.0
 */
package de.fhg.aisec.mark.ui;

import com.google.inject.Injector;
import de.fhg.aisec.mark.ui.internal.MarkActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MarkDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MarkActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MarkActivator activator = MarkActivator.getInstance();
		return activator != null ? activator.getInjector(MarkActivator.DE_FHG_AISEC_MARK_MARKDSL) : null;
	}

}
