# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
name: MARK Eclipse plugin

on: push

jobs:
  # Ridiculous quirks to work around https://github.community/t5/GitHub-API-Development-and/GitHub-package-registry-as-Maven-repo-trouble-uploading-artifact/td-p/28832/page/3
  #
  # tl;dr: Github actions for package releases are broken
  #
  github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.12      
        uses: actions/setup-java@v1
        with:
          java-version: 1.12

      - name: Build with Maven
        run: mvn -B clean -B package -f de.fraunhofer.aisec.mark.parent --file pom.xml -DskipTests

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
              de.fraunhofer.aisec.mark.parent/de.fraunhofer.aisec.mark/target/de.fraunhofer.aisec.mark-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     # - name: Deploy to GitHub package
     #   env:
     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #   run: |
     #     mkdir -p ~/.m2
     #     echo "<settings><servers><server><id>github</id><username>x-access-token</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
     #     cd de.fraunhofer.aisec.mark.parent
     #     mvn -Dmaven.test.skip=true --file pom.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/Fraunhofer-AISEC/codyze-mark-eclipse-plugin -Dtoken=${{ secrets.GITHUB_TOKEN }} deploy
